### ISSUE TITLE
Please remove Denylist

### ISSUE THREAD

**Issue by meccougar** [helium/xorf-generator#11]
Dear Official Member,

I have a Sensecap M1 and 6.7db custom single antenna. And my hotspot working about 1+ year to its location. Nothing to change (antenna, hotspot, location, internet speed or all another one). I can't write removal form for this problem cause I have this massage:

''An owner of this repository has limited the ability to open an issue to users that have contributed to this repository in the past.''

Please check this issue and resolve this problem or unlock the removal issue form please...

My hotspot is Fast Sky Yak    11aUkS265zaJimCF65PVKZ1YNJubPM7wmYz2rp9V2ygEdXCxARa

Have a nice day...

**Comment by madninja** [comment]
> Dear Official Member,
> 
> I have a Sensecap M1 and 6.7db custom single antenna. And my hotspot working about 1+ year to its location. Nothing to change (antenna, hotspot, location, internet speed or all another one). I can't write removal form for this problem cause I have this massage:
> 
> ''An owner of this repository has limited the ability to open an issue to users that have contributed to this repository in the past.''
> 
> Please check this issue and resolve this problem or unlock the removal issue form please...
> 
> My hotspot is Fast Sky Yak 11aUkS265zaJimCF65PVKZ1YNJubPM7wmYz2rp9V2ygEdXCxARa
> 
> Have a nice day...

Wrong location, please submit a request on https://crowdspot.io
