### ISSUE TITLE
112USWDEVr5CCxWuSuUb3PpZ1AqWcXsgcMXoHzcFq2Rh7pecGqY

### ISSUE THREAD

**Issue by Baldrick69** [helium/xorf-generator#12]
My miner has been running over one year, has not been moved from a roof space location and has been recently added to denylist. Please remove

**Comment by madninja** [comment]
This is not where you should submit denylist removal requests. That needs to be done at Crowdspot: https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
