### ISSUE TITLE
112XQ2NcNuXhjbMbZCF9DK9WLVMg8LfSjzNYWePU9ethCMrgqD7H

### ISSUE THREAD

**Issue by kostianuchm** [helium/xorf-generator#14]
Virtual Infrared Seahorse действительно пренадлежит мне, физически установлен в указаной локации, не понимаю почему попал в черный спиок . Удалите его оттуда

**Comment by madninja** [comment]
This is not where you should submit denylist removal requests. That needs to be done at Crowdspot: https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
