### ISSUE TITLE
116Yk5oqqW4ZDDGzWGAGF1JLuXQ4FdkK1imSanLqqUpmxtDSJAR

### ISSUE THREAD

**Issue by ahmet1616161616** [helium/xorf-generator#16]

**Comment by ahmet1616161616** [comment]
I did not understand why my account was closed, I have no idea how to open it, can you help?

**Comment by madninja** [comment]
If you mean that a hotspot is on the denylist then: This is not where you should submit denylist removal requests. That needs to be done at Crowdspot: https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
