### ISSUE TITLE
Delyist rhythmic marigold cormorant

### ISSUE THREAD

**Issue by Bayramyyil** [helium/xorf-generator#20]
Hello, do you think my cap helium device has been deleted from the list. I use this device in appropriate conditions. I want it to ope
![IMG_20230902_173406](https://github.com/helium/xorf-generator/assets/144000096/a16682c7-bba0-47c2-ac08-2180ac1d9be3)
![IMG_20230902_173353](https://github.com/helium/xorf-generator/assets/144000096/87726dfe-cd87-4f8d-b1d0-5358e602a2c9)
![IMG_20230902_173347](https://github.com/helium/xorf-generator/assets/144000096/e8028fc8-e133-418e-961e-ad283830d98e)
n

**Comment by madninja** [comment]
This is not the right place for deny list discussions.. Please go to Discord and the `crowdspot-denylist` channel to ask for analysis of your deny list report card.
