### ISSUE TITLE
Remove hotspot from deny list 

### ISSUE THREAD

**Issue by Goldenbi** [helium/xorf-generator#21]
Dear sir/madam 

my hotspot is in deny list from 5 days i want to remove it.  Acutely i change my flate as well as i change my miner also i try to update the location of my miner but is gose unsuccessful many time then i start it now that location has been changed. Plz remove it from deny list what type of prove u want i can provide  hotspot name Alert Navy Torut 
Address https://app.hotspotty.net/hotspots/112QBY8Cvjse8Vn4JJjDg4zgUJkDvgftvKpQuFDq5K3bkhqSrgFs/rewards

**Comment by madninja** [comment]
This is not the place.. please go into Discord and the crowdspot-denylist channel and ask for help there.

**Comment by Goldenbi** [comment]
Dear all

Can someone share a link of discord channel becoz i search and didn’t found 

Thank u

**Comment by madninja** [comment]
> Dear all Can someone share a link of discord channel becoz i search and didn’t found Thank u

https://discord.gg/helium to get to the helium discord.. then in the technical group you'll see a crowdspot-denylist channel
